{{- if .Values.global.enableCertificateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: all-applications-certificate-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/component: program-certificate
    app.kubernetes.io/instance: {{ .Values.global.appName }}-{{ .Values.global.environment }}
    app.kubernetes.io/managed-by: argocd
  annotations:
    cnpg.io/reload: "true"
    reflector.v1.k8s.emberstack.com/auto-reflects: True
    reflector.v1.k8s.emberstack.com/reflects: all-applications-prod-d1/all-applications-certificate-secret
type: kubernetes.io/tls
{{- end }}